### ISSUE TITLE
Tag and Release, update README.md example to include ?ref=

### ISSUE THREAD

**Issue by bryanlalexander** [GSA/grace-logging#20]

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [grace-logging: Tag and Release, update README.md example to include ?ref= (Issue #20)](https://trello.com/c/zLhRH8c0/1446-grace-logging-tag-and-release-update-readmemd-example-to-include-ref-issue-20)
