### ISSUE TITLE
The input "secops_accounts" is required

### ISSUE THREAD

**Issue by doug-sillex** [GSA/grace-logging#21]
Currently the input "secops_accounts" is listed as optional in the input table. However when trying run without it you will get the following error:

Error: Error running plan: 3 error(s) occurred:

* module.logging.output.secops_role_arn: Resource 'aws_iam_role.secops' not found for variable 'aws_iam_role.secops.0.arn'
* module.logging.output.secops_role_id: Resource 'aws_iam_role.secops' not found for variable 'aws_iam_role.secops.0.id'
* module.logging.output.secops_policy_id: Resource 'aws_iam_role_policy.secops' not found for variable 'aws_iam_role_policy.secops.0.id'

**Comment by briankfitzwater** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [grace-logging: The input "secops_accounts" is required #21](https://trello.com/c/JTtdhsDs/1479-grace-logging-the-input-secopsaccounts-is-required-21)

**Comment by briankfitzwater** [comment]
@doug-sillex I don't have a way to test the output of this module since it conflicts with the logging configured in our development environment.  Let me know if this fixed the problem or not. I'm re-opening the issue until I hear from you.

**Comment by doug-sillex** [comment]
@briankfitzwater Hi Brian,  I just removed the input and tested it out again. It still generates the same errors. Let me know if there is anything I can provide to assist.

**Comment by briankfitzwater** [comment]
@doug-sillex I scheduled a meeting so we can discuss on Google hangouts meet.
